#!/bin/bash
TARGET_DIR="$HOME/Downloads/j2meDash_archive/post-github_archive/"
while read -r local_ref local_sha remote_ref remote_sha; do
    if [ "$remote_sha" = "0000000000000000000000000000000000000000" ]; then
        commit_range="-n 5 $local_sha"
    else
        commit_range="$remote_sha..$local_sha"
    fi
    branch_clean=$(basename "$local_ref" | tr '/' '-')
    for hash in $(git log --reverse --format="%H" "$commit_range" 2>/dev/null); do
        folder_name="commit-${branch_clean}-${hash:0:7}"
        
        if [ ! -d "$TARGET_DIR/$folder_name" ]; then
            echo "[Auto-Export] Extracting incoming commit: $folder_name"
            mkdir -p "$TARGET_DIR/$folder_name"
            git archive "$hash" | tar -x -C "$TARGET_DIR/$folder_name"
        fi
    done
done

