backlightcolor:Disabled
compatfantasyzonefix:off
compatignorevolumechanges:off
compatimmediaterepaints:off
compatoverrideplatchecks:on
compatsiemensfriendlydrawing:off
compattranstooriginonreset:off
dojaversion:200
fontoffset:-3
fps:30
fpshack:Disabled
height:240
phone:Standard
rotate:0
scrheight:400
scrwidth:240
sound:on
soundfont:Default
spdhackm3ghalfres:off
spdhacknoalpha:off
textfont:Default
width:0
