# im testing github workflows

name: Build and push

run-name: "Built by ${{ github.actor }} from commit `${{ github.sha }}`"

on:
  push:
    branches:
      - test-level-loader

permissions:
  contents: write

jobs:
  compile-and-release:
    if: contains(github.event.head_commit.message, '[release]')
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          
      - name: Compile code for Java 8
        shell: cmd
        run: |
          dir
          echo Creating "tmp/classes" folder
          if not exist "classes\" mkdir "tmp\classes"
          echo Creating "sourcelist.txt" file
          dir /s /b src\*.java > sourcelist.txt
          echo Compiling "*.classes" file
          javac -encoding UTF-8 -classpath "lib\*" -sourcepath src -d tmp\classes @sourcelist.txt
          if errorlevel 1 echo failed to compile "*.classes" file && exit /b 1
          echo Packaging into "*.jar" file
          jar cfm j2meDash8.jar src\META-INF\MANIFEST.MF rsc -C tmp\classes .
          if errorlevel 1 echo failed to package "*.jar" file && exit /b 1
          if exist "j2meDash8.jar" move /Y "j2meDash8.jar" "bin"
          echo Successfully compiled code
          goto :eof

      - name: Generate JAD File
        shell: bash
        run: |
          cd bin
          JAR_FILE="j2meDash8.jar"
          JAD_FILE="j2meDash8.jad"
          JAR_SIZE=$(wc -c < "$JAR_FILE" | tr -d ' ')

          cat <<EOF > "$JAD_FILE"
          MIDlet-Name: j2meDash
          MIDlet-Version: 1.0.0
          MIDlet-Vendor: Not RobTop Games AB
          MIDlet-Jar-URL: j2meDash4.jar
          MIDlet-Jar-Size: $JAR_SIZE
          MicroEdition-Profile: MIDP-2.0
          MicroEdition-Configuration: CLDC-1.1
          MIDlet-1: j2meDash,rsc/img/icon.png,j2meDash
          EOF

      - name: Generate SHA-256 Checksum
        shell: bash
        run: |
          cd bin
          sha256sum j2meDash.jar > checksums.txt
          echo "Computed SHA-256:"
          cat checksums.txt

      - name: Verify Checksum
        shell: bash
        run: |
          cd bin
          sha256sum -c checksums.txt

      - name: Create GitHub Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd bin
          gh release create "dev-${{ github.sha }}" \
            checksums.txt \
            j2meDash8.jar \
            j2meDash8.jad \
            --title "Development Release: ${{ github.sha }}" \
            --generate-notes
