# im testing github workflows

name: Automatically commit releases

run-name: ${{ github.repository }}

on:
  push:
    branches:
      - test-level-loader

permissions:
  contents: write

jobs:
  explore-github-actions:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: List files in the repository
        run: |
          dir /s
          shell: cmd
