name: Automatically commit releases
run-name: ${{ github.repository }}
on:
    push:
        branch:
            - test-level-loader
            
permissions:
    contents: write

jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: clone repo
            uses: actions/checkout@v6
            - name: List files in the repository
            run: |
                ls ${{ github.workspace }}
            - run: echo "🍏 This job's status is ${{ job.status }}."
